version: '3'
services:
  api:
    networks:
      - internal
    depends_on:
      - redis
  redis:
    image: redis
    networks:
      - internal
  web:
    networks:
      - internal
    depends_on:
      - api

networks:
  internal:
    name: internal
    driver: bridge